### Connexion d'un user
POST https://api-travel-blog.onrender.com/login
Content-Type: application/json

{
  "mail": "johndoe@mail.com",
  "password": "password"
}

### Connexion d'un user
POST http://localhost:3000/login
Content-Type: application/json

{
  "mail": "johndoe@mail.com",
  "password": "password"
}


