### Accès page infos User [LOCAL]
GET http://localhost:3000/account


### Accès page infos User
GET https://api-travel-blog.onrender.com/account


### Création d'un compte
POST https://api-travel-blog.onrender.com/signup
Content-Type: application/json

{
  "last_name": "TEST",
  "first_name": "Test",
  "avatar": "",
  "mail": "ctest@mail.com",
  "pseudo": "test2", 
  "password": "password",
  "role_id": "2"
}


### Suppression d'un user [LOCAL]
DELETE http://localhost:3000/admin/users/8


### Suppression d'un user
DELETE https://api-travel-blog.onrender.com/account/4


### Modification du last_name d'un user
PATCH https://api-travel-blog.onrender.com/account/lastname/3
Content-Type: application/json

{
  "lastName": "NGUYEN"
}


### Modification du first_name d'un user
PATCH https://api-travel-blog.onrender.com/account/firstname/3
Content-Type: application/json

{
  "firstName": "Vincent"
}


### Modification du mail d'un user
PATCH https://api-travel-blog.onrender.com/account/mail/3
Content-Type: application/json

{
  "mail": "johndoe@mail.com"
}


### Modification du pseudo d'un user
PATCH https://api-travel-blog.onrender.com/account/pseudo/3
Content-Type: application/json

{
  "pseudo": "VincentN"
}


### Modification du password d'un user
PATCH https://api-travel-blog.onrender.com/account/password/1
Content-Type: application/json

{
  "password": "password"
}