### Récupération de tous les users
GET http://localhost:3000/admin/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mbyI6eyJsYXN0X25hbWUiOiJET0UiLCJmaXJzdF9uYW1lIjoiSm9obiIsImF2YXRhciI6InRlc3QiLCJtYWlsIjoiam9obmRvZUBtYWlsLmNvbSIsInBzZXVkbyI6IkpvaG5EIiwicGFzc3dvcmQiOm51bGwsImxhYmVsIjoiQWRtaW4ifSwiaWF0IjoxNzA2MTI5NzMzfQ.CmJcMB2lDld2yFe6d6sJ66SpDgdPQVisCFrKHTYurr0


### Récupération de tous les users
GET https://api-travel-blog.onrender.com/admin/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mbyI6eyJsYXN0X25hbWUiOiJET0UiLCJmaXJzdF9uYW1lIjoiSm9obiIsImF2YXRhciI6InRlc3QiLCJtYWlsIjoiam9obmRvZUBtYWlsLmNvbSIsInBzZXVkbyI6IkpvaG5EIiwicGFzc3dvcmQiOm51bGwsImxhYmVsIjoiQWRtaW4ifSwiaWF0IjoxNzA2MTI5NzMzfQ.CmJcMB2lDld2yFe6d6sJ66SpDgdPQVisCFrKHTYurr0